"""HTML / CSV / Markdown report exports.

All three renderers accept the same payload dict produced by the JSON export
(and stored in SQLite), so they work for both live audits and stored history.
Output files are written owner-only (0600) — they contain target evidence.
"""

from __future__ import annotations

import csv
import html
import io
from pathlib import Path

from honeypot_auditor.reporters.json_export import write_owner_only

_SUFFIX = {"html": ".html", "csv": ".csv", "markdown": ".md"}


def default_report_path(target_ip: str, fmt: str) -> str:
    slug = target_ip.replace(":", "_")
    return f"honeypot-audit-{slug}{_SUFFIX[fmt]}"


def _fmt_cell(value: object, limit: int = 300) -> str:
    text = "" if value is None else str(value)
    return text if len(text) <= limit else text[: limit - 1] + "…"


def _verdict_color(score: float) -> str:
    if score >= 60:
        return "#b22222"
    if score >= 30:
        return "#b8860b"
    return "#0a5c0a"


# -- Markdown ---------------------------------------------------------------


def _md_table(headers: list[str], rows: list[list[str]]) -> str:
    out = ["| " + " | ".join(headers) + " |", "|" + "|".join(["---"] * len(headers)) + "|"]
    for row in rows:
        cells = [c.replace("|", "\\|").replace("\n", " ") for c in row]
        out.append("| " + " | ".join(cells) + " |")
    return "\n".join(out)


def build_markdown(payload: dict) -> str:
    score = float(payload.get("score", 0))
    lines = [
        f"# Honeypot audit — {payload.get('target', '?')}",
        "",
        _md_table(
            ["Field", "Value"],
            [
                ["Target", str(payload.get("target", ""))],
                ["Resolved IP", str(payload.get("resolved_ip", ""))],
                ["Honeyscore", f"{score:.1f}%"],
                ["Threat level", str(payload.get("threat_level", ""))],
                ["Confidence", str(payload.get("confidence", ""))],
                ["Started", str(payload.get("started_at", ""))],
                ["Finished", str(payload.get("finished_at", ""))],
            ],
        ),
        "",
    ]
    if payload.get("tactical_action"):
        lines += [
            f"**Tactical action:** {payload['tactical_action']}",
            "",
            f"_{payload.get('tactical_rationale', '')}_",
            "",
        ]
    triggered = payload.get("triggered") or []
    lines.append(f"## Triggered tells ({len(triggered)})")
    lines.append("")
    if triggered:
        lines.append(
            _md_table(
                ["Indicator", "Category", "Evidence"],
                [
                    [
                        _fmt_cell(t.get("id")),
                        _fmt_cell(t.get("category")),
                        _fmt_cell(t.get("detail")),
                    ]
                    for t in triggered
                ],
            )
        )
    else:
        lines.append("_No honeypot indicators triggered._")
    lines.append("")
    protocols = payload.get("protocol_strategies") or []
    if protocols:
        lines.append("## Per-protocol strategies")
        lines.append("")
        lines.append(
            _md_table(
                ["Protocol", "Ports", "Strategies fired"],
                [
                    [
                        _fmt_cell(p.get("protocol")),
                        ",".join(str(x) for x in p.get("ports", [])),
                        str(
                            sum(
                                1
                                for v in p.values()
                                if isinstance(v, dict) and v.get("status") == "hit"
                            )
                        ),
                    ]
                    for p in protocols
                ],
            )
        )
        lines.append("")
    lines.append("---")
    lines.append("")
    lines.append(f"_Generated by honeypot-auditor · schema {payload.get('schema_version', '?')}_")
    lines.append("")
    return "\n".join(lines)


def export_markdown(payload: dict, path: str | Path) -> Path:
    dest = Path(path)
    dest.parent.mkdir(parents=True, exist_ok=True)
    write_owner_only(dest, build_markdown(payload))
    return dest


# -- CSV ---------------------------------------------------------------------


def build_csv_text(payload: dict) -> str:
    """CSV as text (one row per indicator, triggered first) — for downloads."""
    buffer = io.StringIO()
    _write_indicator_csv(payload, buffer)
    return buffer.getvalue()


def export_csv(payload: dict, path: str | Path) -> Path:
    dest = Path(path)
    dest.parent.mkdir(parents=True, exist_ok=True)
    write_owner_only(dest, build_csv_text(payload))
    return dest


def _write_indicator_csv(payload: dict, buffer: io.StringIO) -> None:
    writer = csv.writer(buffer)
    writer.writerow(
        [
            "target",
            "resolved_ip",
            "score",
            "threat_level",
            "confidence",
            "indicator_id",
            "category",
            "protocol",
            "triggered",
            "skipped",
            "title",
            "detail",
        ]
    )
    common = [
        payload.get("target", ""),
        payload.get("resolved_ip", ""),
        float(payload.get("score", 0)),
        payload.get("threat_level", ""),
        payload.get("confidence", ""),
    ]
    indicators = payload.get("indicators") or []
    triggered_first = sorted(indicators, key=lambda i: (not i.get("triggered"), i.get("id", "")))
    for ind in triggered_first:
        writer.writerow(
            common
            + [
                ind.get("id", ""),
                ind.get("category", ""),
                ind.get("protocol", ""),
                "yes" if ind.get("triggered") else "no",
                "yes" if ind.get("skipped") else "no",
                ind.get("title", ""),
                _fmt_cell(ind.get("detail"), 1000),
            ]
        )


def export_csv_subnet(payload: dict, path: str | Path) -> Path:
    """Subnet CSV: one row per host."""
    dest = Path(path)
    dest.parent.mkdir(parents=True, exist_ok=True)
    buffer = io.StringIO()
    writer = csv.writer(buffer)
    writer.writerow(
        ["target", "host_count", "resolved_ip", "score", "threat_level", "triggered_count"]
    )
    for host in payload.get("hosts") or []:
        writer.writerow(
            [
                payload.get("target", ""),
                payload.get("host_count", ""),
                host.get("resolved_ip", ""),
                float(host.get("score", 0)),
                host.get("threat_level", ""),
                len(host.get("triggered") or []),
            ]
        )
    write_owner_only(dest, buffer.getvalue())
    return dest


# -- HTML ---------------------------------------------------------------------


def build_html(payload: dict) -> str:
    score = float(payload.get("score", 0))
    color = _verdict_color(score)
    triggered = payload.get("triggered") or []
    rows_html = (
        "".join(
            f"<tr><td>{html.escape(str(t.get('id', '')))}</td>"
            f"<td>{html.escape(str(t.get('category', '')))}</td>"
            f"<td>{html.escape(_fmt_cell(t.get('detail')))}</td></tr>"
            for t in triggered
        )
        or "<tr><td colspan=3>No honeypot indicators triggered.</td></tr>"
    )
    proto_rows = "".join(
        f"<tr><td>{html.escape(str(p.get('protocol', '')))}</td>"
        f"<td>{html.escape(','.join(str(x) for x in p.get('ports', [])))}</td>"
        f"<td>{sum(1 for v in p.values() if isinstance(v, dict) and v.get('status') == 'hit')}</td></tr>"
        for p in (payload.get("protocol_strategies") or [])
    )
    tactical = ""
    if payload.get("tactical_action"):
        tactical = (
            f"<p><b>Tactical action:</b> {html.escape(str(payload['tactical_action']))}"
            f" — {html.escape(str(payload.get('tactical_rationale', '')))}</p>"
        )
    return f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Honeypot audit — {html.escape(str(payload.get("target", "")))}</title>
<style>
 body{{font-family:-apple-system,Segoe UI,Roboto,sans-serif;margin:0;background:#f4f4f4;color:#222}}
 .wrap{{max-width:900px;margin:24px auto;background:#fff;padding:24px;border-radius:8px;box-shadow:0 1px 4px #0002}}
 h1{{font-size:1.3rem;margin-top:0}} table{{border-collapse:collapse;width:100%;font-size:.85rem;margin:8px 0 20px}}
 th,td{{text-align:left;padding:6px 8px;border-bottom:1px solid #ddd}}
 th{{background:#fafafa}} .score{{font-size:2rem;font-weight:700}}
 .bar{{height:14px;background:#e0e0e0;border-radius:7px;overflow:hidden;margin:6px 0 18px}}
 .fill{{height:100%;background:{color}}} code{{background:#f6f8fa;padding:1px 4px;border-radius:3px}}
 footer{{color:#888;font-size:.75rem;margin-top:20px}}
</style></head><body><div class="wrap">
<h1>Honeypot audit — <code>{html.escape(str(payload.get("target", "")))}</code></h1>
<table>
<tr><th>Resolved IP</th><td>{html.escape(str(payload.get("resolved_ip", "")))}</td></tr>
<tr><th>Honeyscore</th><td class="score" style="color:{color}">{score:.1f}%</td></tr>
<tr><th>Threat level</th><td><b>{html.escape(str(payload.get("threat_level", "")))}</b></td></tr>
<tr><th>Confidence</th><td>{html.escape(str(payload.get("confidence", "")))}</td></tr>
<tr><th>Window</th><td>{html.escape(str(payload.get("started_at", "")))} → {html.escape(str(payload.get("finished_at", "")))}</td></tr>
</table>
<div class="bar"><div class="fill" style="width:{min(100.0, score):.1f}%"></div></div>
{tactical}
<h2>Triggered tells ({len(triggered)})</h2>
<table><tr><th>Indicator</th><th>Category</th><th>Evidence</th></tr>{rows_html}</table>
<h2>Per-protocol strategies</h2>
<table><tr><th>Protocol</th><th>Ports</th><th>Hits</th></tr>{proto_rows}</table>
<footer>Generated by honeypot-auditor · schema {html.escape(str(payload.get("schema_version", "?")))} ·
authorized targets only</footer>
</div></body></html>
"""


def export_html(payload: dict, path: str | Path) -> Path:
    dest = Path(path)
    dest.parent.mkdir(parents=True, exist_ok=True)
    write_owner_only(dest, build_html(payload))
    return dest


def build_html_subnet(payload: dict) -> str:
    rows = "".join(
        f"<tr><td>{html.escape(str(h.get('resolved_ip', '')))}</td>"
        f"<td>{float(h.get('score', 0)):.1f}%</td>"
        f"<td>{html.escape(str(h.get('threat_level', '')))}</td>"
        f"<td>{len(h.get('triggered') or [])}</td></tr>"
        for h in (payload.get("hosts") or [])
    )
    return f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"><title>Subnet audit — {html.escape(str(payload.get("target", "")))}</title>
<style>body{{font-family:-apple-system,Segoe UI,Roboto,sans-serif;margin:24px;background:#f4f4f4}}
.wrap{{max-width:800px;margin:0 auto;background:#fff;padding:24px;border-radius:8px}}
table{{border-collapse:collapse;width:100%;font-size:.85rem}}th,td{{text-align:left;padding:6px 8px;border-bottom:1px solid #ddd}}</style>
</head><body><div class="wrap"><h1>Subnet audit — {html.escape(str(payload.get("target", "")))}</h1>
<p>{payload.get("host_count", 0)} hosts · {html.escape(str(payload.get("started_at", "")))} → {html.escape(str(payload.get("finished_at", "")))}</p>
<table><tr><th>Host</th><th>Score</th><th>Verdict</th><th>Tells</th></tr>{rows}</table>
</div></body></html>
"""


def build_markdown_subnet(payload: dict) -> str:
    rows = [
        [
            str(h.get("resolved_ip", "")),
            f"{float(h.get('score', 0)):.1f}%",
            str(h.get("threat_level", "")),
            str(len(h.get("triggered") or [])),
        ]
        for h in (payload.get("hosts") or [])
    ]
    return (
        f"# Subnet audit — {payload.get('target', '')}\n\n"
        + _md_table(["Host", "Score", "Verdict", "Tells"], rows)
        + "\n"
    )
