FROM debian:bookworm-slim

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        vsftpd \
        passwd \
    && useradd -m -s /bin/bash hpaudit \
    && echo 'hpaudit:hpaudit_lab' | chpasswd \
    && mkdir -p /var/run/vsftpd/empty /home/hpaudit/ftp \
    && chown hpaudit:hpaudit /home/hpaudit/ftp \
    && printf '%s\n' \
        'listen=YES' \
        'listen_ipv6=NO' \
        'anonymous_enable=NO' \
        'local_enable=YES' \
        'write_enable=YES' \
        'local_umask=022' \
        'dirmessage_enable=YES' \
        'use_localtime=YES' \
        'xferlog_enable=YES' \
        'connect_from_port_20=YES' \
        'chroot_local_user=YES' \
        'allow_writeable_chroot=YES' \
        'secure_chroot_dir=/var/run/vsftpd/empty' \
        'pam_service_name=vsftpd' \
        'pasv_enable=YES' \
        'pasv_min_port=21100' \
        'pasv_max_port=21110' \
        'pasv_address=127.0.0.1' \
        'seccomp_sandbox=NO' \
        > /etc/vsftpd.conf \
    && rm -rf /var/lib/apt/lists/*

EXPOSE 21 21100-21110
CMD ["/usr/sbin/vsftpd", "/etc/vsftpd.conf"]
