protocols = pop3
listen = *, ::
mail_location = maildir:~/Maildir
disable_plaintext_auth = no
auth_mechanisms = plain login
passdb {
  driver = passwd-file
  args = scheme=PLAIN username_format=%u /etc/dovecot/users
}
userdb {
  driver = static
  args = uid=vmail gid=vmail home=/var/mail/%u
}
first_valid_uid = 8
mail_uid = vmail
mail_gid = vmail
ssl = no
log_path = /dev/stderr
info_log_path = /dev/stderr
service pop3-login {
  inet_listener pop3 {
    port = 110
  }
}
service auth {
  unix_listener auth-userdb {
    mode = 0666
  }
}
